services:
  app:
    build: .
    command: uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      AUTH_TOKEN: "your_bearer_token"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.services.sentiment_based_staking_task worker --loglevel=debug
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"# Multi-container setup configuration
